{
  description = "Enclave E2EE KV — reference user-app for ArkLabsHQ/introspector-enclave";

  # NOTE: This flake is a *modified* copy of the framework's Node.js template at
  #   ArkLabsHQ/introspector-enclave: cli/framework_files.go (frameworkFlakeNixNodejs)
  # The single divergence: dontNpmBuild = false, npmBuildScript = "build", and a
  # custom installPhase that picks just the server workspace's outputs (the
  # framework default copies the entire buildNpmPackage tree, which doesn't fit
  # an npm-workspaces layout). When upstream learns to opt in to npm-build via
  # enclave.yaml, this file can shrink back to the standard Node.js template.

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    flake-utils.url = "github:numtide/flake-utils";
    aws-nitro-util.url = "github:monzo/aws-nitro-util";
  };

  outputs = { self, nixpkgs, flake-utils, aws-nitro-util }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ] (system:
      let
        pkgs = import nixpkgs { inherit system; };
        eifPkgs = if system == "x86_64-linux" then pkgs
                  else import nixpkgs { system = "x86_64-linux"; };
        nitro = aws-nitro-util.lib.x86_64-linux;

        # Build config generated by `enclave build` from enclave.yaml.
        configPath = let p = builtins.getEnv "BUILD_CONFIG_PATH"; in
          if p != "" then p else "../.enclave/build-config.json";
        buildCfg = builtins.fromJSON (builtins.readFile configPath);
        appCfg = buildCfg.app;
        runtimeCfg = buildCfg.runtime;

        version = buildCfg.version;
        region = buildCfg.region;
        deployment = buildCfg.prefix;

        resolveInputs = names: map (n: eifPkgs.${n}) names;

        # Enclave supervisor binary, fetched from the framework repo.
        runtime = eifPkgs.buildGoModule {
          pname = "runtime";
          version = buildCfg.version;
          src = eifPkgs.fetchFromGitHub {
            owner = "ArkLabsHQ";
            repo = "introspector-enclave";
            rev = runtimeCfg.rev;
            hash = runtimeCfg.hash;
          };
          sourceRoot = "source/runtime";
          vendorHash = runtimeCfg.vendor_hash;
          subPackages = [ "cmd/runtime" ];
          env.CGO_ENABLED = "0";
          ldflags = [
            "-X" "github.com/ArkLabsHQ/introspector-enclave/runtime.Version=${version}"
          ];
          buildFlags = [ "-trimpath" ];
          tags = [ "netgo" ];
          doCheck = false;
        };

        nodejs = eifPkgs.nodejs_22;

        # User app — fetched from the GitHub coordinates in enclave.yaml.
        # Custom installPhase: pick just the server workspace's outputs.
        upstream-app = eifPkgs.buildNpmPackage ({
          pname = appCfg.binary_name;
          version = buildCfg.version;
          src = eifPkgs.fetchFromGitHub {
            owner = appCfg.nix_owner;
            repo = appCfg.nix_repo;
            rev = appCfg.nix_rev;
            hash = appCfg.nix_hash;
          };
          npmDepsHash = if appCfg.nix_vendor_hash == "" then null else appCfg.nix_vendor_hash;
          dontNpmBuild = false;
          npmBuildScript = "build";
          doCheck = false;

          nativeBuildInputs = resolveInputs (appCfg.nix_native_build_inputs or []);
          buildInputs = resolveInputs (appCfg.nix_build_inputs or []);

          installPhase = ''
            runHook preInstall

            mkdir -p $out/lib/node_modules/${appCfg.binary_name}
            cp -r server/dist     $out/lib/node_modules/${appCfg.binary_name}/dist
            cp -r server/public   $out/lib/node_modules/${appCfg.binary_name}/public
            cp    server/index.js $out/lib/node_modules/${appCfg.binary_name}/index.js
            cp    server/package.json $out/lib/node_modules/${appCfg.binary_name}/package.json

            runHook postInstall
          '';
        } // (if (appCfg.nix_subdir or "") != "" then {
          sourceRoot = "source/${appCfg.nix_subdir}";
        } else {}));

        # Assemble /app: launcher script, runtime supervisor, app sources.
        appDir = eifPkgs.runCommand "enclave-app" { } ''
          mkdir -p $out/app/data $out/app/src

          for dir in ${upstream-app}/lib/node_modules/*/; do
            cp -r "$dir"/* $out/app/src/
          done

          cat > $out/app/${appCfg.binary_name} <<'LAUNCHER'
          #!/bin/sh
          exec node /app/src/index.js "$@"
          LAUNCHER
          chmod +x $out/app/${appCfg.binary_name}

          cp ${runtime}/bin/runtime $out/app/runtime
        '';

        enclaveRootfs = eifPkgs.buildEnv {
          name = "enclave-rootfs";
          paths = [
            appDir
            nodejs
            eifPkgs.busybox
            eifPkgs.cacert
          ];
          pathsToLink = [ "/" ];
        };

        secretsCfgJson = builtins.toJSON (buildCfg.secrets or []);
        appEnvKeysJson = builtins.toJSON (builtins.attrNames (appCfg.env or {}));

        enclaveEnv = let
          appEnvLines = builtins.concatStringsSep "\n"
            (builtins.map (k: "${k}=${builtins.getAttr k appCfg.env}")
              (builtins.attrNames appCfg.env));
        in ''
          PATH=/app:/bin:/usr/bin
          SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
          AWS_REGION=${region}
          ENCLAVE_APP_NAME=${buildCfg.name}
          ENCLAVE_SECRETS_CONFIG=${secretsCfgJson}
          ENCLAVE_MIGRATION_COOLDOWN=${buildCfg.migration_cooldown or "0s"}
          ENCLAVE_PREVIOUS_PCR0=${buildCfg.previous_pcr0 or "genesis"}
          ENCLAVE_KMS_KEY_LOCKED=${if buildCfg.is_kms_key_locked or false then "true" else "false"}
          ENCLAVE_APP_ENV_KEYS=${appEnvKeysJson}
          ENCLAVE_DEPLOYMENT=${deployment}
          ${appEnvLines}
        '';

        eif = nitro.buildEif {
          name = "${buildCfg.name}-enclave";
          inherit version;
          arch = "x86_64";
          kernel = nitro.blobs.x86_64.kernel;
          kernelConfig = nitro.blobs.x86_64.kernelConfig;
          nsmKo = nitro.blobs.x86_64.nsmKo;
          copyToRoot = enclaveRootfs;
          entrypoint = "/app/runtime";
          env = enclaveEnv;
        };

        vendor-hash-check = eifPkgs.buildNpmPackage ({
          pname = "vendor-hash-check";
          version = buildCfg.version;
          src = eifPkgs.fetchFromGitHub {
            owner = appCfg.nix_owner;
            repo = appCfg.nix_repo;
            rev = appCfg.nix_rev;
            hash = appCfg.nix_hash;
          };
          npmDepsHash = "";
          dontNpmBuild = true;
          doCheck = false;
          nativeBuildInputs = resolveInputs (appCfg.nix_native_build_inputs or []);
          buildInputs = resolveInputs (appCfg.nix_build_inputs or []);
        } // (if (appCfg.nix_subdir or "") != "" then {
          sourceRoot = "source/${appCfg.nix_subdir}";
        } else {}));

      in
      {
        packages = {
          inherit upstream-app runtime eif vendor-hash-check;
          default = eif;
        };
      }
    );
}
