# Auto-generated by enclave build — do not edit.
terraform {
  backend "s3" {
    bucket         = "e2ee-server-071680046198-us-east-1"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "dev-e2ee-server-tfstate-lock"
  }
}
